### ISSUE TITLE
Extracting from deep modules hierarchy

### ISSUE THREAD

**Issue by maryo** [peerigon/extract-loader#17]
https://github.com/peerigon/extract-loader/issues/9

```js
/**
 * Executes the given CommonJS module in a fake context to get the exported string. The given module is expected to
 * just return a string without requiring further modules.
 * ...
 */
function runModule(src, filename) {
// ...
```
The given module is expected to just return a string **without requiring further modules**.
So it works when there is no deep hierarchy. So for example when using the interpolate feature of html-loader then something like `${require('partials/header.html')}` from inside `index.html` works but when there is another require inside `partials/header.html` or `<img src="...">`then it fails.

Could it be handled somehow recursively?

EDIT: I'm trying to solve it but I have a problem :P.  I cannot shim the require as it is done in the loader since it's obviously synchronous in node but _loadModule is asynchronous in webpack (what a surprise! :-)). Any idea how to handle it?

@jhnns and others?

The only idea I have is to create a plugin which would extract it from the bundle itself :-/

**Comment by maryo** [comment]
OK. I've solved it bu a VERY UGLY HACK.
https://github.com/maryo/webpack-extract-bundle-text/blob/master/index.js

It does not support hot reloading yet (I'd need to create a loader also and probably solve it simmirarly like this loader does it, just recursively).

**Comment by VladimirGrenaderov** [comment]
You can add require inside runModule:
`
    var sandbox = {
        module: {},
        require: require,
        },
        __webpack_public_path__: publicPath // eslint-disable-line camelcase
    };
`
And it's work, but... fails to resolve inner module because of sandbox context not moved deeper, and relative path (generated by previous loader) become invalid. 

Now I trying to patch this crappy loader to adjust sandbox context.

**Comment by maryo** [comment]
@VladimirGrenaderov: I was trying something simmilar before (I just modified the sandboxed require function a little bit). But I didn't realize how exactly it works. Now i see it. It needs to recursively track all the dependencies using the `loadModule` and `rndPlaceholder` before calling the first runModule.

**Comment by VladimirGrenaderov** [comment]
@maryo so we need run sandbox with each inner module with right version of require, that nows about inner module context. But I have no idea how to extract inner module context information (or the reference to require function).

May be we should summon Tobias? Because exctract-loader is valuable part of webpack, and it just doesn't work with projects contains more 1 css file :(

**Comment by VladimirGrenaderov** [comment]
@sokra, could you give us some advice? How to "extract" content of module with child requires without dirty hacks?

**Comment by jhnns** [comment]
I'll take a look if there's an easy fix 😁 

I have to point out, however, that the extract-loader is designed for simple use-cases only. It has certain limitations. If you want to extract all kind of modules, you should use the [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin).

**Comment by VladimirGrenaderov** [comment]
@jhnns extract-loader helps to handle more complex cases: as en example, I need to access hashed css urls inside js to provide dynamic load in runtime. It's not possible with extract-text without patching bundled js files.

**Comment by jhnns** [comment]
You can try out `v3.0.0`. It tries to evaluate the dependency graph as deep/far as possible. If it doesn't work, your use case is probably out of scope for this loader :(
