### ISSUE TITLE
Extra dependencies when aliases are using

### ISSUE THREAD

**Issue by VladimirGrenaderov** [peerigon/extract-loader#21]
When extract-loader process result from css-loader, it creates dependencies inside sandboxed require:

var absPath = _path2.default.resolve(_path2.default.dirname(_this.resourcePath), resourcePath);
// Mark the file as dependency so webpack's watcher is working
_this.addDependency(absPath);

But if aliases (or other webpack features to redirect request) are used, resourcePath contains "raw" path, not final result. So if I use image with path 'i/some.png' inside CSS, and 'i' - alias to '/some-dir', extract-loader adds phantom dependency for non-existing file 'context-dir/i/some.png'. Those deps make watcher + require context behavior very strange: all modules inside 'context-dir' are invalidated after any changes in this dir!

@jhnns , could you plz add some check before adding dependency? Something like fs.existsSync, for example.

**Comment by jhnns** [comment]
Should be fixed with 1.0.1
