### ISSUE TITLE
Release v1.0.0 on npm?

### ISSUE THREAD

**Issue by danieldiekmeier** [peerigon/extract-loader#24]
I noticed that you released the v1.0.0 here on GitHub, but on npm, the current version is still v0.1.0. The 0.1.0 has a problem with the `require`ing of files with additional loaders, and I think 1.0.0 will fix this.

This was the commit that changed the `require` to a working version: https://github.com/peerigon/extract-loader/commit/e7e361e5c5a841db105396bc663090fc495a4ca8#diff-453648f7ddcea53f5543562ba9bf0d3d

I think this issue is related: https://github.com/webpack-contrib/html-loader/issues/124

**Comment by jhnns** [comment]
Thanks for the heads-up. We had some problems with npm publishing rights but now its published 👍
