### ISSUE TITLE
Support Webpack v4

### ISSUE THREAD

**Issue by mtraynham** [peerigon/extract-loader#32]
I'm getting the following error:

```bash
ERROR in ./src/utils/404/404.extract.html
Module build failed: TypeError: Cannot read property 'output' of undefined
    at Object.extractLoader (./node_modules/extract-loader/src/extractLoader.js:31:72)
 @ ./src/utils/404/404.component.ts 18:15-44
 @ ./src/app/index.routing.ts
 @ ./src/app/index.module.ts
 @ ./src/main.ts
```

This points to the line https://github.com/peerigon/extract-loader/blob/master/src/extractLoader.js#L31, which seems `this.options.output` is no longer defined.

According to the v4 migration guide ([here](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202)), `this.options` has been removed.  Instead of loader-utils and checking `this.options`, you now get all options from `this.query`.  Although, I'm not sure if that carries the `publicPath` option set by the webpack config.  Also not sure what that `publicPath`'s intended usage is here within the context of extract-loader.  Setting it to `null` worked for me.

**Comment by vhmth** [comment]
This fails in v3 (`3.9.1`) as well. Setting to `options: { publicPath: null }` worked too!

**Comment by danielmeneses** [comment]
@mtraynham you are right that solves partially, but I had to set "publicPath" as an empty string otherwise it will concat "null" to all paths if you are using "html-loader" to process paths from lets say "img:src".

**Comment by jhnns** [comment]
Thanks for pointing out 👍. We're about to ship a fix for this, see [PR](https://github.com/peerigon/extract-loader/pull/33).

**Comment by vhmth** [comment]
🎉
