### ISSUE TITLE
Calculation of indexOfQuery incorrect

### ISSUE THREAD

**Issue by andrejpavlovic** [peerigon/extract-loader#50]
https://github.com/peerigon/extract-loader/blob/fb7139af56bb9b61fa6779257b33857b28446ef3/src/extractLoader.js#L93-L95

Shouldn't this be `Math.min` not `Math.max`? Otherwise we might as well write:
```javascript
const indexOfQuery = givenRelativePath.length;
```

I've rolled back to 2.0.1 in order to use oneOf/resourceQuery in webpack config until this is fixed.

**Comment by andresgarza** [comment]
I'm also having issues with this bug.

**Comment by ugrg** [comment]
const relativePathWithoutQuery = givenRelativePath.replace(/(\S+)(?:\?\S+)/,"$1");

**Comment by Jthomas-Roto** [comment]
I'm also having issues with this. Rolling back to 2.0.1 as well.

**Comment by alqh** [comment]
I've open a PR to solve this issue, is anyone able to review and push it through?

**Comment by alqh** [comment]
This issue should be resolved now with the merge of PR

**Comment by alqh** [comment]
@jannikkeye  Can you please mark this issue as resolved too?

**Comment by jannikkeye** [comment]
@alqh Yes, sorry, an oversight on my part 👍
