### ISSUE TITLE
Produced URL is "undefined" rather than expected URL.

### ISSUE THREAD

**Issue by Lattyware** [peerigon/extract-loader#54]
I have [a bug](https://github.com/webpack-contrib/css-loader/issues/864#issue-389031313) that surfaced after updating `css-loader`, but is apparently a bug in `extract-loader`.

The issue:

> After upgrading to 2.0.0 from 1.0.1, I am getting `url(undefined)` in my output CSS where I previously got a valid URL.
> 
> This seems to happen when the URL is referenced multiple times across imported files - after the first reference `undefined` is output.
> 
> * Operating System: Arch Linux
> * Node Version: 11.3.0
> * NPM Version: 6.4.1
> * webpack Version: 4.27.1
> 
> ### Expected Behavior
> 
> The URL should be the same each time it is referenced.
> 
> ### Actual Behavior
> 
> `undefined` is output instead of the URL after the first reference.
> 
> ### Code
> 
> ```css
> @import "./test2";
> 
> .test1 {
>     background: url(../../assets/test.png);
> }
> ```
> 
> ```css
> .test2 {
>     background: url(../../assets/test.png) repeat;
> }
> ```
> 
> Produces:
> 
> ```css
> .test2{background:url(d41d8cd98f00b204e9800998ecf8427e.png) repeat}.test1{background:url(undefined)}
> ```
> 
> ### How Do We Reproduce?
> 
> See [the attached project](https://github.com/webpack-contrib/css-loader/files/2660638/css-loader-bug.zip).

And the response from the `css-loader` project - I assumed it was a problem on their end as it surfaced with the updated version, but apparently not:

> Sorry not related to `css-loader`, problem in `extract-loader`, problem here https://github.com/peerigon/extract-loader/blob/master/src/extractLoader.js#L144, need rewrite logic, maybe use `Object`/`Map` (like `{ __EXTRACT_LOADER_PLACEHOLDER__000_000: 'asset.png' }`) and get asset url based `__EXTRACT_LOADER_PLACEHOLDER__000_000` index.

**Comment by yenshih** [comment]
Severe bug...
Any updates? May I take charge of this repo if it's currently unmaintained? @jhnns

**Comment by yenshih** [comment]
Still no response? :(

**Comment by klesun** [comment]
@yenshih, if you are capable of taking charge of this project, would you mind filing a Pull Request to fix this issue, please? You are our only hope apparently.

**Comment by yenshih** [comment]
I've forked a repo and published `extract-text-loader`. @klesun

**Comment by klesun** [comment]
Oh, cool, thanks, I guess [this](https://www.npmjs.com/package/extract-text-loader) is it.

**Comment by geonanorch** [comment]
Thanks @yenshih , the new `extract-text-loader` fixed it for me.
I saw that there are new commits from @jhnns  on `extract-loader`, so there is still hope that this issue gets fixed at the source and remove the need for a clone.
