### ISSUE TITLE
extract-loader and hot-reload

### ISSUE THREAD

**Issue by beshanoe** [peerigon/extract-loader#8]
I've started using extract-loader in my project and noticed that webpack-dev-server stopped reload page after changes've been made to my html files. I worked when I used plain file-loader. I'm using the same config as you provided in example:
```
module: {
        loaders: [
            {
                test: /\.html$/,
                loaders: [
                    "file?name=[name].[ext]",
                    "extract",
                    "html?" + JSON.stringify({
                        attrs: ["img:src", "link:href"]
                    })
                ]
            }
}
```

**Comment by jhnns** [comment]
I don't think that this is related to the extract-loader because most loaders are not involved in hot-reloading (except the style-loader or the react-hot-loader, for instance). But it depends on your setup. Could you provide a minimal example that demonstrates the problem?

**Comment by beshanoe** [comment]
I've solved the problem. It didn't work because of "file?name=[name].[ext]" line. When I replaced "name" with "hash", hot-reloading started working properly

**Comment by jhnns** [comment]
Thanks for sharing that.
