### ISSUE TITLE
Not working with html-loader interpolation

### ISSUE THREAD

**Issue by angryobject** [peerigon/extract-loader#9]
This loader configuration fails with `TypeError: require(...) is not a function`.

``` javascript
{
   test: /\.html$/,
   loader: 'file?name=[name].[ext]!extract!html?interpolate',
}
```

``` html
<div id="root">${require('./app')}</div>
```

However, if i remove `extract` loader - no errors.

**Comment by jhnns** [comment]
https://github.com/peerigon/extract-loader/pull/20/files provides a test case where html-loader interpolation is used, so that should be no error anymore.
Please re-open if there is still an error :)

**Comment by DamianPereira** [comment]
Having a similar error, using extract-loader 1.0.0 (which has that PR as far as I can tell) and webpack 3.4.1.

I have an index.html with this:

    <link rel="stylesheet" href="${require(`./sass/base.scss`)}">

and I have this in my webpack.config.js

    test: /\.html$/,
      loader: [
        'file-loader?name=[name].html',
        'extract-loader',
        'html-loader?interpolate'

I get this error when trying to run webpack:

```
exports = module.exports = require("../../node_modules/css-loader/lib/css-base.js")(undefined);
                           ^

ReferenceError: require is not defined

```

Should I create a new issue? Or can this one be opened again?
